# This file was generated by GoReleaser. DO NOT EDIT.
cask "yoloai" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "ddb818ac6466e07d0e44818bb61fbe9c525062a6139ec5449d06c80b7e80c11b"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
    on_arm do
      sha256 "cc6ba0a848ccb92e7ce2c663ba049fb8bc165e6cc0e16f991f0571912e3fe907"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
  end

  on_linux do
    on_intel do
      sha256 "75621a1088b1d1e53f34745855b7284f68055142ba6acf562c20adf8a8fd3516"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
    on_arm do
      sha256 "85315df99d9055498377cb89429bd3fb2367d9f20c7309560ece365b885edb35"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
  end

  name "yoloai"
  desc "Sandboxed AI coding agent runner in disposable containers."
  homepage "https://github.com/kstenerud/yoloai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yoloai"
  bash_completion "completions/yoloai.bash"
  fish_completion "completions/yoloai.fish"
  zsh_completion "completions/yoloai.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yoloai"]
    end
  end

  # No zap stanza required

end
