# This file was generated by GoReleaser. DO NOT EDIT.
cask "yoloai" do
  version "0.7.0-rc1"

  on_macos do
    on_intel do
      sha256 "9a7fa7ba6b0f3940abc8d1565c906008bf5073e67ecdc7cfe3dda1bfeea7b218"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
    on_arm do
      sha256 "f3f1b708687b8abf4eb419081e2ea5253f9547f655607de0a6dca66c6f46f2ef"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d4b1c80d3ca48d9bf72c17dddd626af3f7fdd4a8905ac0b451d46020eca326b"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
    on_arm do
      sha256 "a4187e1873f8b7861ee4bb1eb72a08abddeb725dcc2a45c7576992e19950bad1"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
  end

  name "yoloai"
  desc "Sandboxed AI coding agent runner in disposable containers."
  homepage "https://github.com/kstenerud/yoloai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yoloai"
  bash_completion "completions/yoloai.bash"
  fish_completion "completions/yoloai.fish"
  zsh_completion "completions/yoloai.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yoloai"]
    end
  end

  # No zap stanza required

end
