# This file was generated by GoReleaser. DO NOT EDIT.
cask "yoloai" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "dda77bd668a1e21b1dfb826ace07aa447aca6245b33f4cf3eb7c10c3f31abb44"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
    on_arm do
      sha256 "bfdd4b0fe3cee7dc84ef4a210bb49b351075915312588aefc8a5aeb52f1d5c6b"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3424e0787f16b76d25b345eec760aefe0b1c3eda4b8fc4ea18082946b7e63ca"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
    on_arm do
      sha256 "27f17aca49888ea4ab358c127d0a8f1d974e6d870e80ef3a81dff7681c174eda"
      url "https://github.com/kstenerud/yoloai/releases/download/v#{version}/yoloai_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kstenerud/yoloai"
    end
  end

  name "yoloai"
  desc "Sandboxed AI coding agent runner in disposable containers."
  homepage "https://github.com/kstenerud/yoloai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yoloai"
  bash_completion "completions/yoloai.bash"
  fish_completion "completions/yoloai.fish"
  zsh_completion "completions/yoloai.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yoloai"]
    end
  end

  # No zap stanza required

end
